#!/bin/sh

exec deno test --allow-read=logos.js,tests/logos-test.js,friends/logos-multiplayer.js,friends/logos-webrtc.js \
	tests/logos-multiplayer-test.js server/worker-test.js analysis/rounds-test.js analysis/search-test.js
